import Foundation

// MARK: - PredictiveEnvironmentAlert

/// An alert generated by PredictiveAlertEngine when a recurring environmental
/// exceedance is expected within the next 2 hours based on historical patterns
/// (Sprint 25.C).
struct PredictiveEnvironmentAlert: Identifiable, Sendable {

    let id:              UUID
    let roomName:        String
    let sensorTypeRaw:   String

    /// Hours until the expected peak. Negative means the window has already started.
    let hoursUntilPeak:  Double

    let message:         String
    let confidence:      Double
    let weekday:         Int
    let hourOfDay:       Int
    let generatedAt:     Date
}
